/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarnungenRouteImport } from './routes/warnungen'
import { Route as NowcastRouteImport } from './routes/nowcast'
import { Route as MapRouteImport } from './routes/map'
import { Route as HourlyRouteImport } from './routes/hourly'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'

const WarnungenRoute = WarnungenRouteImport.update({
  id: '/warnungen',
  path: '/warnungen',
  getParentRoute: () => rootRouteImport,
} as any)
const NowcastRoute = NowcastRouteImport.update({
  id: '/nowcast',
  path: '/nowcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HourlyRoute = HourlyRouteImport.update({
  id: '/hourly',
  path: '/hourly',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/map': typeof MapRoute
  '/nowcast': typeof NowcastRoute
  '/warnungen': typeof WarnungenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/map': typeof MapRoute
  '/nowcast': typeof NowcastRoute
  '/warnungen': typeof WarnungenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/daily': typeof DailyRoute
  '/hourly': typeof HourlyRoute
  '/map': typeof MapRoute
  '/nowcast': typeof NowcastRoute
  '/warnungen': typeof WarnungenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/daily'
    | '/hourly'
    | '/map'
    | '/nowcast'
    | '/warnungen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/daily'
    | '/hourly'
    | '/map'
    | '/nowcast'
    | '/warnungen'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/daily'
    | '/hourly'
    | '/map'
    | '/nowcast'
    | '/warnungen'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  DailyRoute: typeof DailyRoute
  HourlyRoute: typeof HourlyRoute
  MapRoute: typeof MapRoute
  NowcastRoute: typeof NowcastRoute
  WarnungenRoute: typeof WarnungenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warnungen': {
      id: '/warnungen'
      path: '/warnungen'
      fullPath: '/warnungen'
      preLoaderRoute: typeof WarnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nowcast': {
      id: '/nowcast'
      path: '/nowcast'
      fullPath: '/nowcast'
      preLoaderRoute: typeof NowcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hourly': {
      id: '/hourly'
      path: '/hourly'
      fullPath: '/hourly'
      preLoaderRoute: typeof HourlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  DailyRoute: DailyRoute,
  HourlyRoute: HourlyRoute,
  MapRoute: MapRoute,
  NowcastRoute: NowcastRoute,
  WarnungenRoute: WarnungenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
